Repository ngodat0103/se347, pull requests merged in 2024-12, with the labels that each got.

#34 Sửa login redirect bị sai
  frontend/jira-clone/.env.local
  frontend/jira-clone/.gitignore
  frontend/jira-clone/src/features/auth/components/sign-up-card.tsx
Labels: bug

#35 Sửa email validation không thông báo lỗi đúng
  frontend/jira-clone/src/features/auth/components/sign-in-card.tsx
  frontend/jira-clone/src/features/auth/components/sign-up-card.tsx
Labels: bug

#41 Tự redirect sang dashboard khi đã đăng nhập
  frontend/jira-clone/src/app/page.tsx
  frontend/jira-clone/src/components/workspace-switcher.tsx
  frontend/jira-clone/src/lib/jwt_utils.ts
Labels: enhancement, frontend

#38 workspace update schema
  frontend/jira-clone/src/components/workspace-switcher.tsx
  frontend/jira-clone/src/services/useCreateWorkspace_api.ts
  frontend/jira-clone/src/types/workspace.ts
Labels: refactor

#53 fix(workspace-update): PATCH -> PUT
  package-lock.json
  src/services/useUpdateWorkspace_api.ts
Labels: frontend

#59 Datnvm/logout
  src/features/auth/components/user-button.tsx
  src/services/user_api.ts
Labels: frontend

#67 Datnvm/cr project
  src/app/(dashboard)/layout.tsx
  src/app/(standalone)/workspaces/[workspaceId]/settings/page.tsx
  src/app/(standalone)/workspaces/create/page.tsx
  src/components/navigation.tsx
  src/components/project.tsx
  src/components/sidebar.tsx
  src/components/workspace-switcher.tsx
  src/features/project/components/create-project-form.tsx
  src/features/project/components/create-project-modal.tsx
  src/features/project/components/edit-project-form.tsx
  src/features/project/components/project-avatar.tsx
  src/features/project/hook/use-create-project-modal.ts
  src/features/project/hook/use-project-id.ts
  src/features/project/schema.ts
  src/features/workspace/components/create-workspace-form.tsx
  src/features/workspace/components/create-workspace-modal.tsx
  src/features/workspace/components/update-workspace-form.tsx
  src/features/workspace/components/workspace-avatar.tsx
  src/features/workspace/hook/use-create-workspace-modal.ts
  src/features/workspace/hook/use-workspace-id.ts
  src/features/workspace/schema.ts
  src/services/projectService.ts
  src/types/project.d.ts
Labels: enhancement

#76 [Fronend]: create task
  package-lock.json
  src/app/(dashboard)/layout.tsx
  src/app/(dashboard)/workspaces/[workspaceId]/projects/[projectId]/page.tsx
  src/app/(standalone)/workspaces/[workspaceId]/join/[inviteCode]/page.tsx
  src/app/(standalone)/workspaces/[workspaceId]/projects/[projectId]/settings/page.tsx
  src/app/layout.tsx
  src/components/date-picker.tsx
  src/components/page-error.tsx
  src/components/page-loader.tsx
  src/components/project.tsx
  src/components/query-provider.tsx
  src/components/sidebar.tsx
  src/features/member/components/meber-avatar.tsx
  src/features/project/components/create-project-form.tsx
  src/features/project/components/edit-project-form.tsx
  src/features/project/components/project-avatar.tsx
  src/features/project/hook/use-create-project-modal.ts
  src/features/task/components/TaskViewSwitcher.tsx
  src/features/task/components/create-task-form-wrapper.tsx
  src/features/task/components/create-task-form.tsx
  src/features/task/components/create-task-modal.tsx
  src/features/task/hooks/use-create-task-modal.ts
  src/features/task/hooks/use-edit-task-modal.ts
  src/features/task/hooks/use-task-filters.ts
  src/features/task/hooks/use-task-id.ts
  src/features/task/schemas.ts
  src/features/task/types.ts
  src/features/workspace/components/create-workspace-form.tsx
  src/features/workspace/components/join-workspace-form.tsx
  src/features/workspace/components/update-workspace-form.tsx
  src/services/projectService.ts
  src/services/taskService.ts
  src/services/workspaceService.ts
  src/types/project.d.ts
  src/types/task.d.ts
  src/types/workspace.ts
Labels: enhancement

#82 Redirect sang workspace khi tạo workspace đó
  src/features/workspace/components/create-workspace-form.tsx
Labels: bug

#83 [Frontend]: Redirect sang project và đóng create project modal sau khi tạo project
  src/features/project/components/create-project-form.tsx
Labels: bug

#79 [Fronend]: Tạo table load các tasks
  package-lock.json
  package.json
  src/components/ui/badge.tsx
  src/features/task/components/TaskViewSwitcher.tsx
  src/features/task/components/columns.tsx
  src/features/task/components/create-task-form.tsx
  src/features/task/components/data-filters.tsx
  src/features/task/components/data-table.tsx
  src/features/task/components/task-actions.tsx
  src/features/task/components/task-date.tsx
  src/lib/utils.ts
  src/services/taskService.ts
  src/types/task.d.ts
  src/types/user.d.ts
Labels: frontend

#94 [Fronend]: Task setting
  src/app/(dashboard)/layout.tsx
  src/app/(dashboard)/workspaces/[workspaceId]/projects/[projectId]/page.tsx
  src/components/ui/separator.tsx
  src/features/member/components/meber-avatar.tsx
  src/features/project/components/edit-project-form.tsx
  src/features/project/components/project-avatar.tsx
  src/features/task/components/TaskViewSwitcher.tsx
  src/features/task/components/columns.tsx
  src/features/task/components/create-task/create-task-form-wrapper.tsx
  src/features/task/components/create-task/create-task-form.tsx
  src/features/task/components/create-task/create-task-modal.tsx
  src/features/task/components/edit-task/edit-task-form-wrapper.tsx
  src/features/task/components/edit-task/edit-task-form.tsx
  src/features/task/components/edit-task/edit-task-modal.tsx
  src/features/task/components/task-actions.tsx
  src/features/workspace/components/create-workspace-form.tsx
  src/features/workspace/components/members-list.tsx
  src/features/workspace/components/update-workspace-form.tsx
  src/services/projectService.ts
  src/services/taskService.ts
  src/services/userService.ts
  src/services/workspaceService.ts
  src/types/task.d.ts
Labels: enhancement, frontend

#108 [Frontend:project-analytics]: add
  package-lock.json
  src/app/(dashboard)/workspaces/[workspaceId]/projects/[projectId]/page.tsx
  src/app/(standalone)/workspaces/[workspaceId]/projects/[projectId]/settings/page.tsx
  src/components/analytics-card.tsx
  src/components/analytics.tsx
  src/features/project/components/edit-project-form.tsx
  src/features/task/components/TaskViewSwitcher.tsx
  src/features/task/components/create-task/create-task-form.tsx
  src/features/task/components/data-kanban.tsx
  src/features/task/components/edit-task/edit-task-form.tsx
  src/features/task/schemas.ts
  src/features/workspace/components/join-workspace-form.tsx
  src/features/workspace/components/members-list.tsx
  src/services/projectService.ts
  src/services/taskService.ts
  src/services/workspaceService.ts
  src/types/project.d.ts
  src/types/workspace.ts
Labels: enhancement

#118 [Frontend:task]: Fix null assigneee
  src/app/(dashboard)/workspaces/[workspaceId]/projects/[projectId]/tasks/page.tsx
  src/features/task/components/columns.tsx
  src/features/task/components/task-overview.tsx
Labels: frontend

#119 [Fronend:my-task]: Thêm my-task, chỉ load những tasks mà authenticated user được assigned
  src/app/(dashboard)/workspaces/[workspaceId]/projects/[projectId]/page.tsx
  src/app/(dashboard)/workspaces/[workspaceId]/tasks/page.tsx
  src/features/task/components/TaskViewSwitcher.tsx
  src/services/taskService.ts
Labels: enhancement, frontend

#129 [Frontend:task:calendar]: Thêm task detail khi mở ở chế độ calendar ( trước là 404)
  src/features/task/components/event-card.tsx
  src/features/task/components/kanban-card.tsx
Labels: enhancement

#126 Ntyl/data calendar
  package-lock.json
  package.json
  src/features/member/components/meber-avatar.tsx
  src/features/task/components/TaskViewSwitcher.tsx
  src/features/task/components/data-calendar.css
  src/features/task/components/data-calendar.tsx
  src/features/task/components/event-card.tsx
  src/features/task/components/kanban-card.tsx
  src/services/taskService.ts
  src/types/task.ts
Labels: enhancement
